version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/go/src/myginapp
      - go-modules:/go/pkg/mod
    ports:
      - "8001:8001"
    depends_on:
      - memcached

  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"

  netdata:
    image: netdata/netdata
    hostname: netdata
    ports:
      - "19999:19999"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata

volumes:
  go-modules:
  netdataconfig:
  netdatalib:
  netdatacache:
